test-2

diff --git a/.github/workflows/packer-ami-build.yml b/.github/workflows/packer-ami-build.yml
--- a/.github/workflows/packer-ami-build.yml
+++ b/.github/workflows/packer-ami-build.yml
@@ -51,26 +51,27 @@ jobs:
 
       - name: Build application artifact
         run: |
+          pwd
           mkdir artifacts
           zip -r artifacts/webapp.zip .
         continue-on-error: true
 
-      - name: Install Packer
-        run: |
-          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
-          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
-          sudo apt-get update && sudo apt-get install packer
+      # - name: Install Packer
+      #   run: |
+      #     curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
+      #     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+      #     sudo apt-get update && sudo apt-get install packer
 
-      - name: Run Packer init
-        run: packer init ./packer-ami
+      # - name: Run Packer init
+      #   run: packer init ./packer-ami
 
       # - name: Build Packer AMI
       #   run: packer build ./packer-ami
 
-  protect-ami:
-    runs-on: ubuntu-latest
-    needs: build-ami
+  # protect-ami:
+  #   runs-on: ubuntu-latest
+  #   needs: build-ami
 
-    steps:
-      - name: Fail the workflow if any previous job failed
-        run: exit 1
+  #   steps:
+  #     - name: Fail the workflow if any previous job failed
+  #       run: exit 1
